# ss代理相关设置
server:
  port: 2086
  method: aes-256-cfb
  password: 123456
# 内网映射相关设置
lannet:
  # 内网穿透映射/转发策略：关闭：-1；全部转发至内网：1 (默认)；指定域名转发至内网 0
  lanStrategy: -1
  # 内网穿透映射/转发服务器端口，默认2087
  lanPort: 2087
  # 内网穿透/映射域名，不指定的话默认"mynetylan.adolphor.com"，此域名下的所有请求，会转发到运行LAN服务的 "127.0.0.1"
  lanHostName: mynetylan.adolphor.com
