# to use native NIO lib, default false
nativeNio: false
# ss proxy configuration
server:
  # ss proxy port
  port: 2086
  # ss encrypt/decrypt method
  method: aes-256-cfb
  # ss encrypt/decrypt password
  password: 123456
# lan net configuration
lannet:
  # lan server port, opened to be connected by lan client
  port: 2087
  # encrypt/decrypt method
  method: none
  # encrypt/decrypt password
  password: none
  # lan net strategy
  # -1：close,do NOT transmit msg to lan net
  # 1 (default)：transmit all msg to lan net
  # 0：transmit designated domains's msg to lan net (TODO)
  proxyStrategy: 1
  # the local address of lan server, all the msg request to lanHostName will be transmitred to "127.0.0.1" of lan server machine
  lanHostName: mynetylan.adolphor.com
